### Create Event
POST http://localhost:8080/rest/events
Accept: application/json
Content-Type: application/json

{
  "title": "abc"
}

### Get Event
GET http://localhost:8080/rest/events/1
Accept: application/json

### Get All Events
GET http://localhost:8080/rest/events
Accept: application/json

### Update Event
PUT http://localhost:8080/rest/events/1
Accept: application/json
Content-Type: application/json

{
  "id":1,
  "userIds": [1],
  "title":"Birthday Party"

}

### Delete event by id
DELETE http://localhost:8080/rest/events/1
Accept: application/json

### Get all expenses in an event
GET http://localhost:8080/rest/events/1/allexpenses
Accept: application/json


### Add user to event
POST http://localhost:8080/rest/events/1/users
Accept: application/json
Content-Type: application/json

{
  "name": "Mik Mettemaker",
  "email": "mik@example.com",
  "iban": "ibann",
  "bic": "bicc"
}


### Delete user from event
DELETE http://localhost:8080/rest/events/1/users/1
Accept: application/json

### Get all users in event
GET http://localhost:8080/rest/events/1/users
Accept: application/json

### Get specific user in event
GET http://localhost:8080/rest/events/1/users/1
Accept: application/json