### Create Event
POST http://localhost:8080/rest/events
Accept: application/json
Content-Type: application/json

{
  "title": "abc",
  "users": [1]
}

### Get Event
GET http://localhost:8080/rest/events/2
Accept: application/json

### Get All Events
GET http://localhost:8080/rest/events
Accept: application/json

### Update Event
PUT http://localhost:8080/rest/events/2
Accept: application/json
Content-Type: application/json

{
  "id":2,
  "userIds": [2, 3],
  "title":"Birthday Party"

}

### Delete event by id
DELETE http://localhost:8080/rest/events/1
Accept: application/json
