### Create Expense
POST http://localhost:8080/rest/expenses
Accept: application/json
Content-Type: application/json

{
  "amount": 25,
  "description": "Taxi",
  "payer": null,
  "date": null,
  "event": null
}

### Update Expense
PUT http://localhost:8080/rest/expenses/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "amount": 28,
  "description": "Cake",
  "payer": null,
  "date": null,
  "event": null
}


