### Create Expense
POST http://localhost:8080/rest/events/2/expenses
Accept: application/json
Content-Type: application/json

{
  "amount": 25,
  "description": "Taxi",
  "payerId": 1,
  "split-between": [1,2]
}

### Update Expense
PUT http://localhost:8080/rest/events/1/expenses/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "amount": 32,
  "description": "salut",
  "payerId": 1,
  "date": "2024-03-28"
}

### Get Expenses
GET http://localhost:8080/rest/events/2/expenses
Accept: application/json
Content-Type: application/json

### Delete Expense
DELETE  http://localhost:8080/rest/events/1/expenses/1
Accept: application/json
Content-Type: application/json
