### Create User
POST http://localhost:8080/rest/users
Accept: application/json
Content-Type: application/json

{
  "name": "Slavic",
  "email": "V.Guzun-1@student.tudelft.nl",
  "iban": "11111111",
  "bic": "123"
}

### Update User
PUT http://localhost:8080/rest/users/2
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "name": "Iulia",
  "email": "iuliasl05@gmail.com",
  "iban": "5",
  "bic": "6"
}

### Get User
GET http://localhost:8080/rest/users/1
Accept: application/json

### Get All Users
GET http://localhost:8080/rest/users
Accept: application/json
